### ISSUE TITLE
support to be required by npm

### ISSUE THREAD

**Issue by chinesedfan** [kaelzhang/hashstate#2]
I know this is a cortex package. If set dependencies like cortex.dependencies, it is possible to be required by npm?

**Comment by kaelzhang** [comment]
Yes, I has already been an npm package at the very beginning.

**Comment by chinesedfan** [comment]
But you didn't set dependencies. Can you add and publish?

**Comment by chinesedfan** [comment]
landed in v0.1.1

**Comment by kaelzhang** [comment]
oh, no. You should not add `util` to npm dependencies.

I will rollback 7539522.

**Comment by chinesedfan** [comment]
Sorry, I forgot they are build-in modules.

**Comment by chinesedfan** [comment]
I recall why I want to add those built-in dependencies! Because I want to use this package in webpack.
